---
title: "songs"
author: "Tea Unnebäck"
date: "2022-10-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Helan går

Helan går, sjung hopp faderallanlej  
Helan går, sjung hopp faderallanlej  
Och den som inte helan tar  
han heller inte halvan får  
Helan går, sjung hopp faderallanlej  
  
## Helan går in english  
*Melodi: Helan går*  
  
Hell and gore, chop hop father Allan Allan ley.  
Hell and gore, chop hop father Allan Allan ley.  
Oh handsome in the hell and tar,  
and hell are in the half and four.  
Hell and gore, chop hop father Allan ley.  
  
## Mera brännvin  
*Melodi: Internationalen*  
  
Mera brännvin i glasen,  
mera glas på vårt bord.  
Mera bord på kalasen,  
mer kalas på vår jord.  
Mera jordar med måne,  
mera måne i mars.  
Mera marscher till Skåne,  
mera Skåne gud bevars!  
  
## Spritbolaget  
*Melodi: Du kära lille snickerbo’*  
  
Till spritbolaget ränner jag  
och bankar på dess port.  
Jag vill ha nåt’ som bränner bra  
och gör mig sketfull fort.  
Expediten sade godda’,  
hur gammal kan min herre va?  
Har du nåt legg ditt fula drägg?  
Kom hit igen när du fått skägg.  
  
Nej, detta var ju inte bra,  
jag ska bli full i kväll!  
Då plötsligt en idé jag fick,  
de har ju sprit på Shell.  
Många flaskor stod där på rad.  
Och nu ska jag bli full och glad.  
Den röda drycken åkte ner.  
Nu kan jag inte se nåt mer.  
  
## Om cykling med mera  
*Melodi: Väva Vadmal*  
  
Man cyklar för lite.  
Man röker för mycket.  
Och man är fasen så liberal  
när det gäller maten och spriten.  
Jag borde slutat för längesedan  
men denna sup är så liten.  
Vad tjänar att hyckla?  
Tids nog får man cykla.  
  
## Siffervisan  
*Melodi: Ritsch, ratsch*  
  
1, 2, 75, 6, 7, 75, 6, 7, 75, 6, 7  
1, 2, 75, 6, 7, 75, 6, 7, 73  
107, 103, 102  
107, 6, 19, 27  
17, 18, 16, 15  
13, 19, 14, 17  
19, 16, 15, 11  
8, 47!  
  
## Jag har aldrig har var’t på snusen  
*Melodi: O, hur saligt att få vandra*  
  
Jag har aldrig var’t på snusen,  
aldrig rökat en cigarr, halleluja!  
Mina dygder äro tusen,  
inga syndiga laster jag har.  
Jag har aldrig sett nåt naket,  
inte ens ett litet nyfött barn.  
Mina blickar går mot taket,  
därmed undgår jag frestarens garn.  
Halleluja, Halleluja …  
  
Baccus spelar på gitarren,  
satan spelar på sitt handklaver.  
Alla djävlar dansar tango.  
Säg, vad kan man väl önska sig mer?  
Jo! Att alla bäckar vore brännvin,  
Fyrisån var full av bayerskt öl.  
Konjak i varenda rännsten,  
och punsch i varendaste pöl.  
Och mera öl, och mera öl …  
  
## Bordeaux, Bordeaux  
*Melodi: I sommarens soliga dagar*  
  
Jag minns än idag hur min fader,  
kom hem ifrån staden så glader,  
och rada upp flaskor på rader,  
och sade sen som så: Bordeaux, Bordeaux!  
Han tog ett glas,  
kom i extas,  
och sedan blev det stort kalas.  
Och vi små glin,  
ja vi drack vin,  
som första klassens fyllesvin.  
Och dansade runt uppå bordet  
och skrek så vi blev blå: Bordeaux, Bordeaux!  
  
## Feta fransyskor  
*Melodi: Tomtarnas julmarsch*  
  
Feta fransyskor som svettas om fötterna,  
de trampar druvor som sedan skall jäsas till vin.  
Transpirationen viktig e’  
ty den ger fin bouquet.  
Vårtor och svampar följer me’,  
men vad gör väl de’?  
  
För,  
vi vill ha vin, vill ha vin, vill ha mera vin!  
Även om följderna bli att vi må lida pin.  
Flaskan och glaset gått i sin  
Hit med vin, mera vin  
Tror ni att vi är fyllesvin?  
  
JA! (Fast större)  
  
## Var nöjd med ölen  
*Melodi: Var nöjd med allt som livet ger*  
  
Var nöjd med allt som ölen ger,  
och även om du dubbelt ser.  
Glöm bort bekymmer sorger och besvär.  
Var glad och nöjd för vet du vad,  
en folköl gör ju ingen glad.  
Var nöjd med ölen som vi dricker här.  
  